//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Invenco.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class HistoryMovomentLog
    {
        public int HistoryMovomentLogID { get; set; }
        public int History_InvertID { get; set; }
        public string History_Where_from { get; set; }
        public string History_Where_to { get; set; }
        public System.DateTime History_Date_Mov { get; set; }
    
        public virtual Inventory_History Inventory_History { get; set; }
    }
}
