//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Invenco.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Invertarization
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Invertarization()
        {
            this.MovomentLog = new HashSet<MovomentLog>();
        }
    
        public int InvertNumber { get; set; }
        public int MarkersID { get; set; }
        public string name { get; set; }
        public string Category { get; set; }
        public System.DateTime StartDate { get; set; }
        public string cabinet { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<bool> WrittenOff { get; set; }
        public string StatusName { get; set; }
        public byte[] Image_Invertarization { get; set; }
    
        public virtual Markers Markers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MovomentLog> MovomentLog { get; set; }
    }
}
