//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Invenco.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inventory_History
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Inventory_History()
        {
            this.HistoryMovomentLog = new HashSet<HistoryMovomentLog>();
        }
    
        public int History_InventoryID { get; set; }
        public int HistoryMarkerID { get; set; }
        public string Name { get; set; }
        public string Category { get; set; }
        public System.DateTime StartDate { get; set; }
        public string cabinet { get; set; }
        public System.DateTime EndDate { get; set; }
        public string StatusName { get; set; }
        public byte[] Image_invertarization { get; set; }
    
        public virtual HistoryMarker HistoryMarker { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HistoryMovomentLog> HistoryMovomentLog { get; set; }
    }
}
