//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Invenco.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PETBASEEntities : DbContext
    {
        public PETBASEEntities()
            : base("name=PETBASEEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Category> Category { get; set; }
        public virtual DbSet<HistoryMarker> HistoryMarker { get; set; }
        public virtual DbSet<HistoryMovomentLog> HistoryMovomentLog { get; set; }
        public virtual DbSet<Inventory_History> Inventory_History { get; set; }
        public virtual DbSet<InventoryStatus> InventoryStatus { get; set; }
        public virtual DbSet<Invertarization> Invertarization { get; set; }
        public virtual DbSet<Markers> Markers { get; set; }
        public virtual DbSet<MovomentLog> MovomentLog { get; set; }
        public virtual DbSet<Person_data> Person_data { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
