//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Invenco.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class MovomentLog
    {
        public int IdMovomentLog { get; set; }
        public int InvertNumber { get; set; }
        public string Where_from { get; set; }
        public string Where_to { get; set; }
        public System.DateTime DateMov { get; set; }
    
        public virtual Invertarization Invertarization { get; set; }
    }
}
