//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Invenco.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class MovomentLog
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MovomentLog()
        {
            this.Invertarization = new HashSet<Invertarization>();
            this.Invertarization1 = new HashSet<Invertarization>();
        }
    
        public int IdMovomentLog { get; set; }
        public string Where_from { get; set; }
        public string Where_to { get; set; }
        public System.DateTime DateMov { get; set; }
        public int InvertNumber { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Invertarization> Invertarization { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Invertarization> Invertarization1 { get; set; }
    }
}
